name: CI
on:
  pull_request:
  push:
jobs:
  UI_UT:
    runs-on:
      - ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: script
        run: |
          npm install
          npm run test
